# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whCvcEzoFKMYGsOXPMnyBMQKKONGCTaX
"""

!pip install janome

from janome.tokenizer import Tokenizer

def analyze_japanese_text(text):
    tokenizer = Tokenizer()
    tokens = list(tokenizer.tokenize(text))

    print("--- JAPANESE TEXT ANALYSIS REPORT ---")
    print(f"Original Text: {text}")
    print(f"Total Words Detected: {len(tokens)}\n")

    print("Word Breakdown:")
    unique_kanji = set()

    for token in tokens:
        surface = token.surface
        part_of_speech = token.part_of_speech.split(',')[0]
        print(f" - Word: {surface} | Type: {part_of_speech}")

        for char in surface:
            if '\u4e00' <= char <= '\u9fa5':
                unique_kanji.add(char)

    print("\nUnique Kanji Characters Found:")
    print(", ".join(unique_kanji) if unique_kanji else "No Kanji found.")

# Direct Japanese text analysis
sample_text = "私はPythonと日本語を勉強しています。"
analyze_japanese_text(sample_text)

!pip install requests

import requests
from datetime import datetime

def convert_jpy(amount_jpy, target_currency="USD"):
    # Live currency exchange rates API
    url = "https://api.exchangerate-api.com/v4/latest/JPY"

    try:
        response = requests.get(url)
        data = response.json()

        rate = data['rates'].get(target_currency.upper())
        if not rate:
            print(f"Currency {target_currency} not supported.")
            return

        converted = amount_jpy * rate
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        log_entry = f"[{timestamp}] ¥{amount_jpy:,} JPY = ${converted:.2f} {target_currency.upper()} (Rate: {rate})\n"

        # Save to a local file
        with open("conversion_history.txt", "a", encoding="utf-8") as file:
            file.write(log_entry)

        print("--- CONVERSION SUCCESSFUL ---")
        print(log_entry.strip())
        print("Logged to 'conversion_history.txt'")

    except Exception as e:
        print(f"Error fetching exchange rates: {e}")

# Example Run: Convert 50,000 Yen to USD
convert_jpy(50000, "USD")

